import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'es';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    pt: {
        back_to_dashboard: '← Voltar ao Painel',
        travelers_count: 'Viajantes',
        planning_phase: 'Fase de Planejamento',
        active_trip: 'Viagem Ativa',
        completed: 'Concluída',
        goal_vs_saved: 'Meta vs Guardado',
        available_budget: 'Orçamento Disponível',
        total_spent: 'Total Gasto',
        itinerary: 'Roteiro',
        no_cities: 'Nenhuma cidade adicionada. Busque e adicione seu primeiro destino!',
        add_destination: 'Adicionar Destino',
        search_city_placeholder: 'Digite o nome da cidade (ex: Orlando)...',
        manage_travelers: 'Gerenciar Viajantes',
        traveler_name: 'Nome do viajante...',
        add: 'Adicionar',
        no_travelers: 'Nenhum viajante adicionado.',
        cancel: 'Cancelar',
        save_changes: 'Salvar Alterações',
        budget_savings: 'Orçamento e Reservas',
        define_goals: 'Defina suas metas e guarde dinheiro antes da viagem começar.',
        add_category: 'Adicionar Categoria',
        no_categories: 'Nenhuma categoria definida. Adicione passagens, hotel, alimentação, etc.',
        saved: 'Guardado',
        deposit: 'Depositar',
        new_category: 'Nova Categoria',
        category_name: 'Nome da Categoria',
        how_to_budget: 'Como deseja orçar?',
        general_exp: 'Gasto Geral',
        one_total_goal: 'Uma meta total para toda a viagem',
        per_person: 'Por Pessoa',
        set_indiv_goals: 'Metas específicas para cada viajante',
        total_budget_goal: 'Meta de Orçamento Total',
        traveler_list_goals: 'Lista de Viajantes e Metas Individuais',
        create_category: 'Criar Categoria',
        deposit_savings: 'Depositar Economias',
        amount_to_save: 'Valor a Guardar',
        date: 'Data',
        note: 'Nota (Opcional)',
        confirm_deposit: 'Confirmar Depósito',
        plan_new_trip: 'Planejar Nova Viagem',
        trip_name: 'Nome da Viagem',
        primary_destination: 'Destino Principal',
        start_date: 'Data de Início',
        end_date: 'Data de Término',
        currency: 'Moeda',
        create_trip: 'Criar Viagem',
        logout: 'Sair',
        my_trips: 'Minhas Viagens',
        no_trips_yet: 'Nenhuma viagem ainda!',
        start_planning: 'Comece a planejar sua próxima aventura.',
        expenses: 'Gastos',
        funding_transfers: 'Funding e Transferências',
        route_cities: 'Roteiro e Cidades',
        hello: 'Olá',
        team_settings: 'Configurações da Equipe',
        delete_trip: 'Excluir Viagem',
        delete_confirm_msg: 'Tem certeza que deseja excluir esta viagem? Todos os dados relacionados serão removidos permanentemente.',
        no_cities_yet: 'Nenhuma cidade ainda',
        trip_name_placeholder: 'ex: Eurotrip 2026, Verão no Japão...',
        primary_dest_placeholder: 'Para onde você vai? (ex: Orlando)',
        optional: 'Opcional',
        recent_expenses: 'Gastos Recentes',
        expense: 'Gasto',
        record_expense: 'Registrar Gasto',
        expense_tracker_title: 'Rastreador de Gastos Ativos',
        expense_tracker_desc: 'Acompanhe seus gastos diários em relação ao orçamento disponível.',
        active_tab_empty: 'Nenhuma categoria definida ainda. Vá para a aba de Planejamento para configurá-las.',
        left: 'restante',
        daily_goal: 'Meta Diária',
        days: 'dias',
        day: 'dia',
        spent_so_far: 'Gasto até agora',
        amount_spent: 'Valor Gasto',
        description_place: 'Descrição / Local',
        desc_placeholder: 'ex: Starbucks, Uber',
        save_expense: 'Salvar Gasto',
        funding_rebalancing: 'Financiamento e Rebalanceamento',
        funding_desc: 'Adicione dinheiro extra via dinheiro/crédito ou mova fundos entre categorias.',
        transfer: 'Transferir',
        add_funds: 'Adicionar Fundos',
        extra_funding: 'Financiamento Extra',
        transfers_in: 'Transferências Recebidas',
        transfers_out: 'Transferências Realizadas',
        current_available: 'Disponível Atual',
        amount: 'Valor',
        method: 'Método',
        cash_debit: 'Dinheiro / Débito',
        credit_card: 'Cartão de Crédito',
        description: 'Descrição',
        transfer_title: 'Transferir Entre Categorias',
        from: 'De',
        to: 'Para',
        select_target: 'Selecione o destino...',
        amount_to_move: 'Valor a Mover',
        transfer_funds: 'Transferir Fundos',
        remove: 'Remover',
        remove_city_confirm: 'Remover esta cidade da viagem?',
        loading_trip_details: 'Carregando detalhes da viagem...',
        category_name_placeholder: 'ex: Passagens Aéreas, Hotel de Luxo...',
        note_placeholder: 'De onde veio este dinheiro?',
        rebalance: 'Rebalanceamento',
        diff_categories_alert: 'As categorias devem ser diferentes'
    },
    en: {
        back_to_dashboard: '← Back to Dashboard',
        travelers_count: 'Travelers',
        planning_phase: 'Planning Phase',
        active_trip: 'Active Trip',
        completed: 'Completed',
        goal_vs_saved: 'Goal vs Saved',
        available_budget: 'Available Budget',
        total_spent: 'Total Spent',
        itinerary: 'Itinerary',
        no_cities: 'No cities added yet. Search and add your first destination!',
        add_destination: 'Add Destination',
        search_city_placeholder: 'Type city name (e.g. Orlando)...',
        manage_travelers: 'Manage Travelers',
        traveler_name: 'Traveler name...',
        add: 'Add',
        no_travelers: 'No travelers added.',
        cancel: 'Cancel',
        save_changes: 'Save Changes',
        budget_savings: 'Travel Budgeting',
        define_goals: 'Set your goals and track your pre-trip savings.',
        add_category: 'Add Category',
        no_categories: 'No budget categories yet. Create categories like Flight, Hotel, or Food.',
        saved: 'Pre-trip Saved',
        deposit: 'Deposit',
        new_category: 'New Category',
        category_name: 'Category Name',
        how_to_budget: 'How would you like to budget?',
        general_exp: 'General',
        one_total_goal: 'One total goal for the whole trip',
        per_person: 'Per Person',
        set_indiv_goals: 'Set specific goals for each traveler',
        total_budget_goal: 'Total Budget Goal',
        traveler_list_goals: 'Traveler List & Individual Goals',
        create_category: 'Create Category',
        deposit_savings: 'Piggy Bank Deposit',
        amount_to_save: 'Amount to Save',
        date: 'Date',
        note: 'Note (Optional)',
        confirm_deposit: 'Confirm Deposit',
        plan_new_trip: 'Plan a New Trip',
        trip_name: 'Trip Name',
        primary_destination: 'Primary Destination',
        start_date: 'Start Date',
        end_date: 'End Date',
        currency: 'Currency',
        create_trip: 'Create Trip',
        logout: 'Logout',
        my_trips: 'My Trips',
        no_trips_yet: 'No trips yet!',
        start_planning: 'Start planning your next adventure.',
        expenses: 'Expenses',
        funding_transfers: 'Funding & Transfers',
        route_cities: 'Route & Cities',
        hello: 'Hello',
        team_settings: 'Team Settings',
        delete_trip: 'Delete Trip',
        delete_confirm_msg: 'Are you sure you want to delete this trip? All related data will be permanently removed.',
        no_cities_yet: 'No cities yet',
        trip_name_placeholder: 'e.g. Eurotrip 2026, Summer in Japan...',
        primary_dest_placeholder: 'Where are you going? (e.g. Orlando)',
        optional: 'Optional',
        recent_expenses: 'Recent Expenses',
        expense: 'Expense',
        record_expense: 'Record Expense',
        expense_tracker_title: 'Active Expense Tracker',
        expense_tracker_desc: 'Track your daily spending against your available budget.',
        active_tab_empty: 'No categories defined yet. Go to the Planning tab to set them up.',
        left: 'left',
        daily_goal: 'Daily Goal',
        days: 'days',
        day: 'day',
        spent_so_far: 'Spent So Far',
        amount_spent: 'Amount Spent',
        description_place: 'Description / Place',
        desc_placeholder: 'e.g. Starbucks, Uber',
        save_expense: 'Save Expense',
        funding_rebalancing: 'Funding & Rebalancing',
        funding_desc: 'Add extra money via cash/credit or move funds between categories.',
        transfer: 'Transfer',
        add_funds: 'Add Funds',
        extra_funding: 'Extra Funding',
        transfers_in: 'Transfers In',
        transfers_out: 'Transfers Out',
        current_available: 'Current Available',
        amount: 'Amount',
        method: 'Method',
        cash_debit: 'Cash / Debit',
        credit_card: 'Credit Card',
        description: 'Description',
        transfer_title: 'Transfer Between Categories',
        from: 'From',
        to: 'To',
        select_target: 'Select Target...',
        amount_to_move: 'Amount to Move',
        transfer_funds: 'Transfer Funds',
        remove: 'Remove',
        remove_city_confirm: 'Remove this city from the trip?',
        loading_trip_details: 'Loading trip details...',
        category_name_placeholder: 'e.g. Flight Tickets, Luxury Hotel...',
        note_placeholder: 'Where did this money come from?',
        rebalance: 'Rebalance',
        diff_categories_alert: 'Categories must be different'
    },
    es: {
        back_to_dashboard: '← Volver al Panel',
        travelers_count: 'Viajeros',
        planning_phase: 'Fase de Planificación',
        active_trip: 'Viaje Activo',
        completed: 'Completado',
        goal_vs_saved: 'Meta vs Guardado',
        available_budget: 'Presupuesto Disponible',
        total_spent: 'Total Gastado',
        itinerary: 'Itinerario',
        no_cities: 'No se han añadido ciudades. ¡Busca y añade tu primer destino!',
        add_destination: 'Añadir Destino',
        search_city_placeholder: 'Escribe el nombre de la ciudad (ej: Orlando)...',
        manage_travelers: 'Gestionar Viajeros',
        traveler_name: 'Nombre del viajero...',
        add: 'Añadir',
        no_travelers: 'No hay viajeros añadidos.',
        cancel: 'Cancelar',
        save_changes: 'Guardar Cambios',
        budget_savings: 'Presupuesto y Ahorros',
        define_goals: 'Establece tus metas y ahorra dinero antes de que comience el viaje.',
        add_category: 'Añadir Categoría',
        no_categories: 'No hay categorías definidas. Añade vuelos, hotel, comida, etc.',
        saved: 'Guardado',
        deposit: 'Depositar',
        new_category: 'Nueva Categoría',
        category_name: 'Nombre de la Categoría',
        how_to_budget: '¿Cómo prefieres presupuestar?',
        general_exp: 'General',
        one_total_goal: 'Una meta total para todo el viaje',
        per_person: 'Por Persona',
        set_indiv_goals: 'Metas específicas para cada viajero',
        total_budget_goal: 'Meta de Presupuesto Total',
        traveler_list_goals: 'Lista de Viajeros y Metas Individuales',
        create_category: 'Crear Categoría',
        deposit_savings: 'Depositar Ahorros',
        amount_to_save: 'Cantidad a Ahorrar',
        date: 'Fecha',
        note: 'Nota (Opcional)',
        confirm_deposit: 'Confirmar Depósito',
        plan_new_trip: 'Planificar Nuevo Viaje',
        trip_name: 'Nombre del Viaje',
        primary_destination: 'Destino Principal',
        start_date: 'Fecha de Inicio',
        end_date: 'Fecha de Fin',
        currency: 'Moneda',
        create_trip: 'Crear Viaje',
        logout: 'Cerrar Sesión',
        my_trips: 'Mis Viajes',
        no_trips_yet: '¡Aún no hay viajes!',
        start_planning: 'Comienza a planificar tu próxima aventura.',
        expenses: 'Gastos',
        funding_transfers: 'Financiamiento y Transferencias',
        route_cities: 'Ruta y Ciudades',
        hello: 'Hola',
        team_settings: 'Ajustes del Equipo',
        delete_trip: 'Eliminar Viaje',
        delete_confirm_msg: '¿Estás seguro de que deseas eliminar este viaje? Todos los datos relacionados se eliminarán permanentemente.',
        no_cities_yet: 'Sin ciudades aún',
        trip_name_placeholder: 'ej: Eurotrip 2026, Verano en Japó...',
        primary_dest_placeholder: '¿A dónde vas? (ej: Orlando)',
        optional: 'Opcional',
        recent_expenses: 'Gastos Recientes',
        expense: 'Gasto',
        record_expense: 'Registrar Gasto',
        expense_tracker_title: 'Seguimiento de Gastos Activos',
        expense_tracker_desc: 'Sigue tus gastos diarios comparados con el presupuesto disponible.',
        active_tab_empty: 'Aún no hay categorías definidas. Ve a la pestaña de Planificación para configurarlas.',
        left: 'restante',
        daily_goal: 'Meta Diaria',
        days: 'días',
        day: 'día',
        spent_so_far: 'Gastado hasta ahora',
        amount_spent: 'Cantidad Gastada',
        description_place: 'Descripción / Lugar',
        desc_placeholder: 'ej: Starbucks, Uber',
        save_expense: 'Guardar Gasto',
        funding_rebalancing: 'Financiamiento y Reequilibrio',
        funding_desc: 'Añade dinero extra en efectivo/crédito o mueve fondos entre categorías.',
        transfer: 'Transferir',
        add_funds: 'Añadir Fondos',
        extra_funding: 'Financiamiento Extra',
        transfers_in: 'Transferencias Recibidas',
        transfers_out: 'Transferencias Realizadas',
        current_available: 'Disponible Actual',
        amount: 'Cantidad',
        method: 'Método',
        cash_debit: 'Efectivo / Débito',
        credit_card: 'Tarjeta de Crédito',
        description: 'Descripción',
        transfer_title: 'Transferir Entre Categorías',
        from: 'De',
        to: 'Para',
        select_target: 'Seleccionar Destino...',
        amount_to_move: 'Cantidad a Mover',
        transfer_funds: 'Transferir Fondos',
        remove: 'Eliminar',
        remove_city_confirm: '¿Eliminar esta ciudad del viaje?',
        loading_trip_details: 'Cargando detalles del viaje...',
        category_name_placeholder: 'ej: Billetes de avión, Hotel de lujo...',
        note_placeholder: '¿De dónde vino este dinero?',
        rebalance: 'Reequilibrio',
        diff_categories_alert: 'Las categorías deben ser diferentes'
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>('pt');

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang && (savedLang === 'pt' || savedLang === 'en' || savedLang === 'es')) {
            setLanguageState(savedLang);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
